#! /usr/bin/env python
import sys, numpy as n

# PSA-64, JD2455903...
A_ = [0,16,8,24,4,20,12,28]
B_ = [i+1 for i in A_]
C_ = [i+2 for i in A_]
D_ = [i+3 for i in A_]
ANTPOS_5903 = n.array([A_, B_, C_, D_])

# PSA-128, JD2456240...
A_ = [49,41,47,19,29,28,34,51]
B_ = [10, 3,25,48,24,55,27,57]
C_ = [ 9,58, 1, 4,17,13,56,59]
D_ = [22,61,35,18, 5,32,30,23]
E_ = [20,63,42,37,40,14,54,50]
F_ = [43, 2,33, 6,52, 7,12,38]
G_ = [53,21,15,16,62,44, 0,26]
H_ = [31,45, 8,11,36,60,39,46]
ANTPOS_6240 = n.array([A_, B_, C_, D_,E_,F_,G_,H_])

ANTPOS = ANTPOS_6240

bls = {}
for ri in range(ANTPOS.shape[0]):
    for ci in range(ANTPOS.shape[1]):
        for rj in range(ANTPOS.shape[0]):
            for cj in range(ci,ANTPOS.shape[1]):
                sep = '%d,%d' % (rj-ri, cj-ci)
                i,j = ANTPOS[ri,ci], ANTPOS[rj,cj]
                if i > j: i,j = j,i
                bls[sep] = bls.get(sep,[]) + [(i,j)]

rv = []
for sep in sys.argv[1:]:
    rv += [','.join(['%d_%d' % (i,j) for i,j in bls[sep]])]

print ','.join([r for r in rv if len(r) > 0])

