data:
    root:       /users/alanman/eorsky/scripts/
    template:   'eorsky_out/three_short_bl/eorsky_24.00hours_Nside256_uv'
pspec:
#    baseline: '[(0,11),(0,12),(11,12)]'
    baseline: '[(0,11),(11,12),(0,12)]'
catalog:
    sigma: 2.0   #Kelvin
    Nside: 256   #Input map
out:
    overwrite : False
    outdir: 'results'
    version: 'eorsky_3blshort_nside256'
