# coding: utf-8
# don't ask me why the above line is here. I was getting a weird error saying
# that I was using a non-ascii character on line 11 and this fixed it.....
import aipy as a, numpy as n, pylab as p
import capo as C
import useful_functions as uf
import os

# in gsm directory run
# $ gfortran -ffixed-line-length-none gsmmanyfreqs.f -o gsmmf.sh
# edit args.dat 
# put all the following on the first line: 
# 	> the prefix of all the data files it will make,  
# 	> the lowest frequency that you’d like to simulate (in MHz), 
#	> the frequency resolution (so the delta-nu between adjacent simulations), 
# 	> the total number of frequencies you’d like to simulate.
# then run  
# $ ./gsmmf.sh
# it will put all the data files in the current directory
# next you need to convert the .dat files to .fits 
# you can run gsm_to_fits(filename.dat) individual file or loop over many
# files in a folder using gsm_to_fits_loop()
# to make a color map of the fits data, go to the terminal and do:
# $ plot_map.py '/Users/mpresley/soft/gsm/data_100MHz_150MHz/hi1001.fits'

def gsm_to_fits(filename):
	"""
	Takes a .dat file from the global sky model and converts it to a .fits
	file in the same directory
	"""
	dat = n.loadtxt(filename)
	heal = a.healpix.HealpixMap(nside=512)
	heal.map = dat
	heal.to_fits(filename.replace('.dat','.fits'))

def gsm_to_fits_loop(folderpath):
	"""
	Loops over all .dat files in a folder and runs gsm_to_fits to convert them
	to a .fits file stored in the same location
	"""
	for filename in os.listdir(folderpath):
		if '.dat' in filename:
			print filename
			gsm_to_fits(os.path.join(folderpath,filename))

def import_gsm_data(folderpath='/Users/mpresley/soft/gsm/data_100MHz_150MHz/',savedata=True):
	"""
	Takes a folder containing the args.dat file used for gsmanyfreqs.f and the .fits 
	files generated by running gsmanyfreqs.f and gsm_to_fits_loop. 

	Returns a 2d array with the healpix data for different frequencies in the columns.
	Also returns a 1d array telling the frequency in MHz that corresponds to each column. 
	"""
	ff = open(folderpath+'args.dat','r')
	args = ff.readline()
	datpre,nui,nustep,nunum = args.split(' ')
	nui=int(nui);nustep=int(nustep);nunum=int(nunum)
	freqs = n.linspace(nui,nunum*nustep+nui,num=nunum,endpoint=True)
	for ii in range(nunum):
		print ii
		healmap = a.map.Map(fromfits='{0}{1}{2}.fits'.format(folderpath,datpre,1001+ii))
		if ii==0:
			data = n.zeros([healmap.map.map.shape[0],nunum])
		data[:,ii] = healmap.map.map
	if savedata: n.savez_compressed(folderpath+'map_data',data=data,freqs=freqs)
	return data, freqs

def power_fit_gsm_data(data,freqs,savefolderpath=None):
	params = n.zeros([data.shape[0],3])
	for ii in range(data.shape[0]):
		print ii
		# amp        index           redchi
		params[ii,0], params[ii,1], _, _, params[ii,2] = uf.power_law_lstsq_fit(freqs,data[ii,:])
	if savefolderpath!=None: n.savez_compressed(savefolderpath+'power_fit_params',amp=params[:,0],index=params[:,1],redchi=params[:,2])
	return params
# make a healpix map 
#name = a.map.Map(fromfits='/Users/mpresley/soft/gsm/data_100MHz_150MHz/hi1001.fits')
# data component of map -- numpy array
#data = name.map.map

# pulls up healpix code in ipython
# aipy.healpix.HealpixMap??

#indexmap = a.map.Map
#indexmap.map.map = params[:,1]



if __name__=='__main__':
	#filename = '/Users/mpresley/soft/gsm/data_100MHz_150MHz/hi1001.dat'
	#gsm_to_fits_loop('/Users/mpresley/soft/gsm/data_100MHz_150MHz/')
	#data,freqs = import_gsm_data()
	#p.plot(freqs,data[500,:])
	f = n.load('/Users/mpresley/soft/gsm/data_100MHz_150MHz/map_data.npz')
	data = f['data']
	freqs = f['freqs']
	params = power_fit_gsm_data(data,freqs,savefolderpath='/Users/mpresley/soft/gsm/data_100MHz_150MHz/')
	print params
	p.plot(range(params.shape[0]),params[:,1],c='b')
	p.plot(range(params.shape[0]),params[:,2],c='g')
	p.show()

	#n.savez('/Users/mpresley/soft/gsm/data_100MHz_150MHz/map_data',data=data,freqs=freqs)


