#!/usr/global/paper/bin/python

import aipy as a, numpy as n, pylab as p, sys, os, optparse
from mpl_toolkits.basemap import Basemap

o = optparse.OptionParser()
o.set_usage('plot_beam.py [options] mapfile')
o.set_description(__doc__)
a.scripting.add_standard_options(o, cmap=True, max=True, drng=True,cal=True)
o.add_option('--tol', dest='tol', type='float', default=1.e-5,
    help="Tolerance for clean.  Default is 1e-5.")
o.add_option('--npix', dest='npix',type='int', default=1000,
    help="Number of pixels used in the sky image.")
o.add_option('--nmodes', dest='nmodes',type='int',default=6,
    help="Number of CLEAN components to use in the smooth reconstruction.")
o.add_option('--savefits', dest='savefits', action='store_true',
    help="Save the smooth beam as a HEALPix fits file.")

opts,args = o.parse_args(sys.argv[1:])
center = opts.npix/2

h = a.map.Map(fromfits=args[0])
print 'SCHEME:', h.scheme()
print 'NSIDE:', h.nside()

im = a.img.Img(size=(opts.npix*.4),res=.4)
x,y,z = im.get_top()

data = h.map[x,y,z]
kern = h.wgt[x,y,z]
old = data.shape
data.shape = x.shape
kern.shape = x.shape

mdata = n.where(x.mask == 1,0,data)
#mkern = n.where(kern == 0,kern,1)
mkern = n.where(x.mask == 1,1,kern)

mdata = a.img.recenter(mdata,(center,center))
mkern = a.img.recenter(mkern,(center,center))

_data = n.fft.fft2(mdata)
_kern = n.fft.fft2(mkern)

_beam = a.deconv.clean(_data,_kern,maxiter=10,stop_if_div=False,tol=opts.tol)

beam = n.fft.ifft2(_beam[0])*(_beam[0].size)
res = n.fft.ifft2(_beam[1]['res'])

_sbeam = a.img.recenter(_beam[0],(-center,-center))
_sbeam[:,:center-opts.nmodes] = 0.
_sbeam[:,center+opts.nmodes:] = 0.
_sbeam[:center-opts.nmodes,:] = 0.
_sbeam[center+opts.nmodes:,:] = 0.
#_sbeam[27:37,27:37] = 0.
sbeam = n.fft.ifft2(a.img.recenter(_sbeam,(center,center)))*(_sbeam.size)

outname = args[0].replace('.fits','.smoothe.fits')
outfile = a.map.Map(h.nside())
xx,yy,zz = x.compressed(),y.compressed(),z.compressed()
#print xx.shape,yy.shape,zz.shape
hbeam = n.ma.array(a.img.recenter(sbeam,(-center,-center)),mask=x.mask).compressed()
hbeam.shape = xx.shape
outfile.add((xx,yy,zz),1,hbeam)
if opts.savefits == True:
    outfile.to_fits(outname,clobber=True)

coeffs = _sbeam[center-opts.nmodes:center+opts.nmodes,center-opts.nmodes:center+opts.nmodes]
#coeffs = _sbeam
n.savez(outname.replace('.fits','.npz'),coeffs=coeffs)

p.subplot(131)
p.imshow(n.abs(beam))
p.colorbar()
p.subplot(132)
p.imshow(n.abs(res))
p.colorbar()
p.subplot(133)
p.imshow(n.abs(sbeam),interpolation='Nearest')
p.colorbar()

p.show()
