#! /usr/bin/env python
"""
Antenna pad number to grid number thingy.
3 Dec 2011
DCJ IIS
"""
import sys

#The mapping between antenna number and grid location. 
#Letters north to south, numbers west to east
grid_num = {'A0':49,'B0':10,'C0': 9,'D0':22,
            'A1':41,'B1':03,'C1':58,'D1':61,
            'A2':47,'B2':25,'C2':01,'D2':35,
            'A3':19,'B3':48,'C3':04,'D3':18,
            'A4':29,'B4':24,'C4':17,'D4':05,
            'A5':28,'B5':55,'C5':13,'D5':32,
            'A6':34,'B6':27,'C6':56,'D6':30,
            'A7':51,'B7':57,'C7':59,'D7':23  
}

print grid_num[sys.argv[-1]],
