#!/bin/bash
#
RETVAL=0;

start() {
echo “Starting still_task_server”
start-stop-daemon --start -m --pidfile=/data/still_taskserver.pid  -b --exec /home/obs/bin/still_taskserver.py --  /data/ --logfile=/data/still_taskserver.log
}

stop() {
echo “Stopping still_task_server”
start-stop-daemon --stop  --pidfile=/data/still_taskserver.pid still_taskserver.py
rm /data/still_taskserver.pid
}

restart() {
stop
start
}

case $1 in
start)
  start 
;;
stop)
  stop
;;
restart)
  restart
;;
*)
  echo "Usage: $0 {start|stop|restart}"
;;
esac
